### ISSUE TITLE
gettext strings missing after use of case statement in erb

### ISSUE THREAD

**Issue by JasonBarnabe** [translation/rails#44] opened 2021-11-22 21:47 UTC
Ruby 2.6.6
Rails 6.1.4.1
translation: 1.27

With this code:
```erb
<%= _('jason test 1') %>
<% case 1 %>
<% end %>
<%= _('jason test 2') %>
```
Only `jason test 1` appears in app.pot after a sync.

With this code:

```erb
<%= _('jason test 1') %>
<% case 1
end %>
<%= _('jason test 2') %>
```
Both `jason test 1` and `jason test 2` appear in app.pot.

**Comment by MichaelHoste** [comment] 2021-11-23 14:20
I was able to reproduce it.

I'm not really sure how and where to fix this issue.

I printed the source code that is sent from the ERB parser to the Ruby parser ([here](https://github.com/ruby-gettext/gettext/blob/006b181fab0a7948b3fb4ba09297fe50ec0f9d5a/lib/gettext/tools/parser/erb.rb#L73)) and I got this:

First file:

```ruby
#coding:UTF-8
_erbout = +''; _erbout.<<(( _('jason test 1') ).to_s); _erbout.<< "\n".freeze
;  case 1 ; _erbout.<< "\n".freeze
;  when 2 ; _erbout.<< "\n".freeze
;  end ; _erbout.<< "\n".freeze
; _erbout.<<(( _('jason test 2') ).to_s); _erbout.<< "\n".freeze
; _erbout
```

Second file:

```ruby
#coding:UTF-8
_erbout = +''; _erbout.<<(( _('jason test 1') ).to_s); _erbout.<< "\n".freeze
;  case 1
when 2
end ; _erbout.<< "\n".freeze
; _erbout.<<(( _('jason test 2') ).to_s); _erbout.<< "\n".freeze
; _erbout
```

(I added `when 2` to avoid a syntax error when executing the code)

The first Ruby code seems wrong. When it is executed, it breaks after `case 1 ;` and the second sentence is never executed.

My guess is that the issue is related to the ERB parser! There is not much we can do here or at the [GetText](https://github.com/ruby-gettext/gettext/) gem, sorry about this.

**Comment by MichaelHoste** [comment] 2021-11-23 14:24
It appears that my analysis was correct and that it is a known ERB issue:
 
 * https://gist.github.com/davidphasson/91613
 * https://stackoverflow.com/a/5282650/1243212

I close this ticket since it's not really related to this project.

**Closed by MichaelHoste** 2021-11-23 14:24 UTC

**Comment by JasonBarnabe** [comment] 2021-11-23 14:39
> (I added when 2 to avoid a syntax error when executing the code)

Sorry about, I was minimizing the test case and I guess I didn't try to execute it.

```erb
<%= _('jason test 1') %>
<% case 2 %>
<% when 1 %>foo!
<% when 2 %>bar!
<% end %>
<%= _('jason test 2') %>
```

The links you provide certainly sound like the issue, but when I execute this code, it seems work fine; output is:

```
jason test 1
bar!
jason test 2
```

And yet my app.pot does not contain `jason test 2`.

**Comment by MichaelHoste** [comment] 2021-11-23 14:45
Your code still contain the issue mentioned in the links.

To fix it, you have 2 solutions:

```ruby
<%= _('jason test 1') %>
<% case 2
when 1 %>foo!
<% when 2 %>bar!
<% end %>
<%= _('jason test 2') %>
```

or (the cleanest!):

```ruby
<%= _('jason test 1') %>
<% case 2 -%>
<% when 1 %>foo!
<% when 2 %>bar!
<% end %>
<%= _('jason test 2') %>
```

(notice the `-%>`)

I tested them both and they worked.

**Comment by JasonBarnabe** [comment] 2021-11-23 14:48
Yes, I understand my code is in the same format as mentioned in the links, but when I execute it, I don't see any issue in the output. The case statement seems to work. I'm just trying to understand in what way it's broken, as far as what it outputs.

**Comment by MichaelHoste** [comment] 2021-11-23 15:05
I'm not really sure. 

I just passed your code as argument into the ERB parser used in `GetText` and it returned me this Ruby code:

```ruby
_erbout = +''; _erbout.<<(( _('jason test 1') ).to_s); _erbout.<< "\n".freeze
;  case 2 ; _erbout.<< "\n".freeze
;  when 1 ; _erbout.<< "foo!\n".freeze
;  when 2 ; _erbout.<< "bar!\n".freeze
;  end ; _erbout.<< "\n".freeze
; _erbout.<<(( _('jason test 2') ).to_s); _erbout.<< "\n".freeze
; _erbout
```

`_erbout` only contains the first string.

However, with the 2 "fixed" syntaxes, the generated Ruby code works and returns both strings in `_erbout`:

```ruby
_erbout = +''; _erbout.<<(( _('jason test 1') ).to_s); _erbout.<< "\n".freeze
;  case 2 
 when 1 ; _erbout.<< "foo!\n".freeze
;  when 2 ; _erbout.<< "bar!\n".freeze
;  end ; _erbout.<< "\n".freeze
; _erbout.<<(( _('jason test 2') ).to_s); _erbout.<< "\n".freeze
; _erbout
```

I don't know why it doesn't work with GetText but works with your template.

Maybe Rails calls the ERB parser differently? Or do some post-treatment with the parsed Ruby code to avoid this specific error?

**Comment by MichaelHoste** [comment] 2021-11-23 15:24
Nice catch! Rails `5.1+` uses Erubi and before that it was Erubis.

That explains it.

I'm not sure why GetText still uses ERB. Maybe they want to avoid more external dependencies for non-rails projects?

Except this specific case, do you think Erubi could be a real improvement to [GetText](https://github.com/ruby-gettext/gettext), or it wouldn't matter much?

**Comment by JasonBarnabe** [comment] 2021-11-23 15:28
I don't really know the difference. [Here's the commit](https://github.com/rails/rails/commit/7da8d76206271bdf200ea201f7e5a49afb9bc9e7) where Rails switched, which includes their reasoning.

**Comment by MichaelHoste** [comment] 2021-11-23 17:39
Here is some WIP on GetText to change the ERB parser to Erubi : https://github.com/MichaelHoste/gettext/commit/32c4d67bc331e1040129c0cd6e82dbb520e453e8

Tests seem OK, I hope that it will not introduce any side-effect. Feel free to test if it solves your specific issue.

**Comment by JasonBarnabe** [comment] 2021-11-23 21:31
translation seems to require `<= 3.3.7` in gettext, so it's not easy to switch to that fork. I guess I could fork translation too to remove the requirement, but I assume it's there for a reason and there may be compatibility issues.

**Comment by MichaelHoste** [comment] 2021-11-23 23:23
`<= 3.3.7` is required because the pluralization rules of some languages have been updated and we still need to decide if we want to support them (`fr` has a new special plural rule for multiple of 1_000_000 and we find it quite stupid. `1000000 emails` or `1000000 d'emails` is not worth the extra-work).

But `> 3.3.7` will already work without any known issue.

We will officially update GetText soon since [this feature](https://github.com/ruby-gettext/gettext/issues/89) is important to us.

**Comment by MichaelHoste** [comment] 2021-12-07 10:45
This issue was also escalated to ERB: https://github.com/ruby/erb/issues/4

**Comment by mfazekas** [comment] 2022-03-24 13:39
We're facing the same issue. Some of our .erb are just missing completely from `translation.io`. 
It would be great if we'd get a warning at least, we could work around the issue by using your fork of get text which uses erubi https://github.com/MichaelHoste/gettext/commit/32c4d67bc331e1040129c0cd6e82dbb520e453e8.

I'd also argue to reopen the bug this is definitely a bug in `translate` gem that should support erb files supported by rails.  And would make it faster to figure out while some translations are missing. Or might be even better open a new issue with explaining what kind of constructs doesn't work and potential workaround, so people don't have to read all the conversation related to the bug.

**Comment by MichaelHoste** [comment] 2022-03-24 13:59
Hi @mfazekas,

I'm sorry about this. This issue was the first time we encountered this ERB parsing bug and we guessed that it must almost never happens. Not a lot of developers use these problematic `case` in their `erb` files. 

Can I ask you which syntax you had a problem with? Is it exactly the same `case` syntax issue, or another one?

As you can see above, the issue was escalated to ERB and it was considered a wontfix to them: https://github.com/ruby/erb/issues/4

I tried to fix it at the level of ruby-gettext by switching ERB for Erubi in this pull request: https://github.com/ruby-gettext/gettext/pull/91

But there is some resistance from the maintainer, even if all the tests are still passing using Erubi. Maybe it would help if you could contribute to the thread by explaining your issue.

Another solution would be to fork GetText just for this, but I'm not sure it's worth it.

**Comment by mfazekas** [comment] 2022-03-24 14:26
@MichaelHoste it seems that 3 files were missing and all of them had case statements, that doesn't look problematic for me.

Some examples:

```erb
<% case @package.current_state %>
<% when "received", "needs_special_handling" %>


...

```

Other: 

```
 <% case @payment.payment_method %>
      <% when "card" %>
```

**Comment by MichaelHoste** [comment] 2022-03-24 15:22
Thank you for your suggestions @mfazekas.

> 1.) Maybe a GetText PR could be changed so it's only and option to use ERUBI - instead of removing ERB and changing to ERUBI. Then your patch would have much less impact, as default behaviour would not change at all.

To be honest, I clearly prefer opinionated solutions. Since Erubi seems objectively better, and is also the default `.erb` parsing library of Rails, that should be possible to always use it instead of ERB in GetText.

But using it as an option could be a great way to move forward with this! I'll investigate this solution 🙂

> 2.) At least a warning would be nice from translate, as otherwise it's hard to detect those issues.

We could scan all the `.erb` files to detect those issues.
But my preference would be to take some time to fix it correctly.

In the meantime, I added this section, hoping that it will help people know about this limitation: https://github.com/translation/rails#limitations

**Comment by MichaelHoste** [comment] 2022-05-20 14:53
The new [1.32 version](https://github.com/translation/rails/releases/tag/v1.32) of this gem is now published, and includes the new Erubi parser from gettext.

This issue should now be completely fixed.

Any feedback would be appreciated @JasonBarnabe and @mfazekas.
